name: Download Twitch Stream

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: 'Twitch Stream URL'
        required: true
        default: 'https://www.twitch.tv/smallant'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: python -m pip install --upgrade yt-dlp

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: Extract Stream Title
      id: extract-title
      run: echo "STREAM_TITLE=$(yt-dlp --get-title ${{ github.event.inputs.stream_url }})" >> $GITHUB_ENV

    - name: Download Stream Segment
      # Attempt to limit download time; this is more illustrative than functional
      # as yt-dlp does not have a built-in way to limit download duration directly
      run: yt-dlp -o "${{ env.STREAM_TITLE }}.%(ext)s" --max-filesize 1872m ${{ github.event.inputs.stream_url }}

    - name: Upload Stream as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.STREAM_TITLE }}
        path: ./*
        
    - name: Trigger Another Workflow or Action via Curl
      run: |
        curl \
          -X POST \
          -H "Authorization: token ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/comprefg/TwitchDL/actions/workflows/download-twitch-stream/dispatches \
          -d '{"ref":"REF", "inputs": {"stream_url": "https://www.twitch.tv/smallant"}}'
      env:
        YOUR_PERSONAL_ACCESS_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
