name: Download Twitch Stream

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: 'Twitch Stream URL'
        required: true
        default: 'https://www.twitch.tv/smallant'
      minute_splits:
        description: 'Download Intervals'
        required: true
        default: "10"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: python -m pip install --upgrade yt-dlp

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: Extract Stream Title
      id: extract-title
      run: echo "STREAM_TITLE=$(yt-dlp --get-title ${{ github.event.inputs.stream_url }})" >> $GITHUB_ENV

    - name: Download Stream
      run: yt-dlp -o "${{ env.STREAM_TITLE }}.%(ext)s" ${{ github.event.inputs.stream_url }}

    - name: Upload Stream as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.STREAM_TITLE }}
        path: ./*
