name: Download Twitch Stream

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: 'Twitch Stream URL'
        required: true
        default: 'https://www.twitch.tv/smallant'

      timeout:
        description: 'timeout'
        required: true
        default: '5h'
        
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: python -m pip install --upgrade yt-dlp

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: Extract Stream Title
      id: extract-title
      run: echo "STREAM_TITLE=$(yt-dlp --get-title ${{ github.event.inputs.stream_url }})" >> $GITHUB_ENV

    - name: Sanitize Stream Title
      run: |
        echo "SANITIZED_TITLE=$(echo $STREAM_TITLE | sed 's/[":<>|*?\\/\r\n]//g')" >> $GITHUB_ENV

    - name: Download Stream Segment
      run: timeout ${{ github.event.inputs.timeout }} yt-dlp -o "${{ env.SANITIZED_TITLE }}.%(ext)s" ${{ github.event.inputs.stream_url }}
      continue-on-error: true

    - name: Upload Stream as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.SANITIZED_TITLE }}
        path: ./*
